# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
#

AguilaBundle:
    resource: "@AguilaBundle/Resources/config/routing.yml"