fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

aguila_static:
    resource: "@AguilaBundle/Controller/StaticController.php"
    type:     annotation

aguila_project:
    resource: "@AguilaBundle/Controller/ProjectController.php"
    type:     annotation

aguila_feature:
    resource: "@AguilaBundle/Controller/FeatureController.php"
    type:     annotation

aguila_task:
    resource: "@AguilaBundle/Controller/TaskController.php"
    type:     annotation

aguila_comment:
    resource: "@AguilaBundle/Controller/CommentController.php"
    type:     annotation